name: blocky

include:
  - docker-compose/backup-db.yml
  - docker-compose/blocky.yml
  - docker-compose/calibre-web-automated.yml
  # - docker-compose/calibre-web.yml # can't be used with cwa
  - docker-compose/grafana.yml
  - docker-compose/lists-download.yml
  - docker-compose/manyfold.yml
  - docker-compose/miniflux.yml
  - docker-compose/prometheus.yml
  - docker-compose/readeck.yml
  - docker-compose/traefik.yml
  - docker-compose/waf.yaml
  - docker-compose/loki.yml
  #######
  # WIP #
  #######
  #- docker-compose/kuma.yml
  #- docker-compose/filebrowser.yml
  #- docker-compose/openbao.yml
  #- docker-compose/vault.yml

networks:
  public:
    name: public_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "192.168.1.90" # Change this to your host IP
