name: lists-download

services:
  lists-download:
    image: shizunge/blocky-lists-updater:latest
    container_name: lists-download
    depends_on:
      traefik:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./lists-download/sources:/sources/sources:ro # Source lists
      - ./lists-download/watch:/web/watch:ro         # Watch lists
      - bld-downloaded:/web/downloaded               # Downloaded lists
      - ./blocky/index.html:/web/index.html:ro       # Fake index file used for health checks
    environment:
      # Possible values are DEBUG INFO WARN ERROR and NONE. Case sensitive.
      BLU_LOG_LEVEL: INFO
      # Add a location to the log messages.
      BLU_NODE_NAME: "{{.Node.Hostname}}"
      # Use an empty BLU_BLOCKY_URL to disable sending POST requests to the lists refresh API of blocky.
      BLU_BLOCKY_URL: http://blocky.local:4000
      # This should be under the BLU_WEB_FOLDER to be read by blocky.
      BLU_DESTINATION_FOLDER: /web/downloaded
      # Define the seconds to wait before the first download.
      BLU_INITIAL_DELAY_SECONDS: 60
      # Set BLU_INTERVAL_SECONDS to 0 to run the lists updater only once then exit.
      BLU_INTERVAL_SECONDS: 86400
      # Blocky won't read the sources files. It reads the downloaded files in the destination folder.
      BLU_SOURCES_FOLDER: /sources
      # Use an empty BLU_WATCH_FOLDER to disable watching lists of domains.
      # This should be under the BLU_WEB_FOLDER to be read by blocky.
      BLU_WATCH_FOLDER: /web/watch
      # Use an empty BLU_WEB_FOLDER to disable the static-web-server.
      BLU_WEB_FOLDER: /web
      # Port used by the static-web-server.
      BLU_WEB_PORT: 8080
    networks:
      - blocky  # <--- This network is used for internal communication between services.
      - public  # <--- This network is used to reach the internet.
      - traefik # <--- This network is used for communication with the traefik reverse proxy.

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/index.html" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.rtr-lists-download.rule: Host(`traefik`) && PathPrefix(`/lists-download`)
      traefik.http.routers.rtr-lists-download.middlewares: stripprefix-lists-download@docker
      traefik.http.routers.rtr-lists-download.entrypoints: web
      traefik.http.middlewares.stripprefix-lists-download.stripprefix.prefixes: /lists-download
      traefik.http.routers.rtr-lists-download.service: svc-lists-download
      traefik.http.services.svc-lists-download.loadbalancer.server.port: 8080
      traefik.job: list_download

    deploy:
      resources:
        limits:
          cpus: '0.50' # Limit CPU usage
          memory: 256M # Limit memory usage
        reservations:
          cpus: '0.25' # Reserve CPU
          memory: 128M # Reserve memory
    dns: 1.1.1.1 # Use Cloudflare DNS since blocky isn't running while it downloads block lists

volumes:
  bld-downloaded: # This volume is used to store downloaded block lists
