name: prometheus
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    depends_on:
      blocky:
        condition: service_healthy
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - blocky
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 64M
        reservations:
          cpus: '0.0025'
          memory: 16M
    expose:
      - '9100'

  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus
    depends_on:
      blocky:
        condition: service_healthy
      node-exporter:
        condition: service_started
      traefik:
        condition: service_healthy
    volumes:
      - prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    #ports:
    #  - "9090:9090"
    networks:
      - traefik
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.rtr-prometheus.rule: PathPrefix(`/prometheus/`) && ClientIP(`192.168.1.0/24`)
      traefik.http.routers.rtr-prometheus.entrypoints: websecure
      traefik.http.routers.rtr-prometheus.tls: true
      traefik.http.routers.rtr-prometheus.middlewares: stripprefix-prometheus@docker
      traefik.http.middlewares.stripprefix-prometheus.stripprefix.prefixes: /prometheus/
      traefik.http.services.svc-prometheus.loadbalancer.server.port: 9090
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.025'
          memory: 128M

volumes:
  prometheus_config:
    # ./prometheus
    driver: local
    driver_opts:
      type: none
      device: ./prometheus
      o: bind
  prometheus_data:
    # driver: local
    # driver_opts:
      # type: tmpfs
      # device: tmpfs
      # o: size=128m
